colorscheme: dark

logo:
  enabled: true
  width: 120
  height: 61
  url: /terraform-netskope-publisher/images/logo.png
  gravatar: false
  grayout: false

nav:
  home:      /
  starter:   /starter/
  admin:     /admin/
  reference: /reference/
  github:    https://github.com/johnneerdael/terraform-netskope-publisher

social_links:
  github: johnneerdael

projects:
  enabled: false

posts_overview:
  show_all_posts: false

copyright:
  start_year: 2026
  end_year:   2026
